/* Prototypes of all decompiled functions (merged from re/protos). Generated by tools/merge_protos.py */
#ifndef ETERNAM_PROTOS_H
#define ETERNAM_PROTOS_H
#include <stdint.h>

void     sub_0053_0000(void);  /* if farcoreleft() < 20000 purge the resource cache (sub_0053_028e) */
void     sub_0053_0016(uint8_t *a, uint8_t *b);  /* swaps the two int16 values *a and *b */
int16_t  sub_0053_003c(int16_t kind, int16_t idx);  /* finds resource-cache slot (DS:0x928, 20x6) with (s8)kind,(s8)idx; returns slot index or -1 */
int16_t  sub_0053_007e(uint8_t *res);  /* 1 if resource ptr is used (+0x16) by a living actor in the current room (on world map [0xa0]==-1: also within 800 of camera 0x1fc2/0x1fc4), else 0 */
void     sub_0053_0112(void);  /* farfree every kind-0 (A??.PAK) cache slot and clear its ptr, unconditionally */
void     sub_0053_0168(uint8_t *res);  /* clears the sprite ptr (+0x16) of actors 1..9 that point to res */
void     sub_0053_01e8(uint8_t *actor);  /* frees the actor's sprite resource from the cache if kind 0 and no other actor uses it */
void     sub_0053_028e(void);  /* purges cache: frees all kind-0 slots whose resource is not in use (sub_0053_007e), detaching actors */
void     sub_0053_030c(int16_t code);  /* fatal error: prints "NO SLOT FREE !!"(0)/"NO MEMORY FREE !!"(1) on screen at 100,100, waits for a key, shuts down/exits */
int16_t  sub_0053_036c(void);  /* returns index of first free (NULL ptr) resource-cache slot, or -1 */
uint8_t *sub_0053_03a5(int16_t kind);  /* returns preloaded resource block for kind 1..7 (1:0x3256 2:0x3286 3:0x17b4 6:0x3262 7:0x3062), else NULL */
uint8_t *sub_0053_0413(uint8_t *pakname, int16_t idx);  /* loads entry idx of a .PAK file (sub_0c66_0003), purging cache/retrying on failure; fatal "NO MEMORY" if still NULL */
uint8_t *sub_0053_0483(int16_t kind, int16_t idx);  /* gets/loads a cached resource: kind 0 = entry idx of A??.PAK, other kinds = preloaded blocks; returns data ptr */
uint8_t *sub_0053_052f(int16_t idx, uint8_t *base);  /* returns base + ((int32*)base)[idx]  (resource directory lookup) */
uint8_t *sub_0053_0564(int16_t i, int16_t j, uint8_t *base);  /* two-level directory lookup: b = base + dir[i]; returns b + ((int32*)b)[j] */
void     sub_0053_05cd(void);  /* pause: if 'P' (scancode 0x19) pressed, wait release then wait for any key/input/button (busy-wait) */
int16_t  sub_0053_05f6(int16_t n);  /* random number 0..n-1 (rand()%n), 0 if n < 2 */
void     sub_0053_0612(void);  /* builds current room's obstacle rectangles (DS:0x1286, count byte 0x1284) from room object list in level data */
void     sub_0053_075b(uint8_t key, uint8_t id);  /* inserts (y-key,id) pair into sorted depth list DSPTR(0x3270); tracks min y in 0x1778 */
void     sub_0053_07ea(void);  /* resets depth list DSPTR(0x3270) with the room's static objects (key = object y, id 0x10) */
void     sub_0053_086b(void);  /* clears game flag arrays DS:0x11bc[100] and DS:0xfbc[256]; sets word 0x11bc = -1 */
void     sub_0053_0895(uint8_t *buf, int32_t len);  /* decrypts buffer in place: buf[i] -= (uint8)(0x5f*(i+1)), i unsigned 32-bit */
void     sub_0053_08f0(uint8_t *dst, int16_t idx, int32_t size);  /* loads text block idx from T.CC4 (sub_03dd_0008) into dst and decrypts it */
void     sub_0053_0925(int16_t n);  /* writes 2-digit level number n into file names A00.PAK, D00.PAK, R00.CC4 */
void     sub_0053_097e(void);  /* frees level data DSPTR(0x3286) and the kind-3 block 0x17b4 (sub_0596_0033) */
uint8_t *sub_0053_0994(uint8_t *base);  /* returns sub-block 4 (palette) of a level data block: sub_0053_052f(4, base) */
void     sub_0053_09a7(int16_t level);  /* loads level: sets 0xa0/0xa2, file names, clip rect, chapter text, D??.PAK data, palette */
void     sub_0053_0a6d(void);  /* per-level-session init: allocs back buffer/depth list/script/text buffers, loads RESID.PAK#1, inits player actor */
void     sub_0053_0b7f(uint8_t *p);  /* farfree(p) (then zeroes its local copy only) */
void     sub_0053_0b9b(void);  /* frees level-session buffers 0x3056,0x177e,0x3270,0x325a,0x3282 (pointers are NOT nulled) */
void     sub_0053_0be7(void);  /* game init: loads RESID.PAK#0 (font etc.), allocs palettes, loads UI text, clears flags, sets player defaults */
void     sub_0053_0cc4(void);  /* copies floor polyline point count (0x1832) to 0xda and rasterizes it into per-column floor-y table DS:0xa68 */
int16_t  sub_0053_0cdd(int16_t v);  /* abs(v) */
void     sub_0053_0cf2(uint8_t *actor, int16_t anim);  /* starts animation anim on actor: frame 0, frame count from sprite data, +0x22=0xff; records player anim in 0x326a */
void     sub_0053_0d68(int16_t idx, int16_t room, uint8_t *sprites);  /* initializes actor idx (standing, facing up, default size/bounds) in room with sprite set */
void     sub_0053_0e27(uint8_t *actor, int16_t dir);  /* sets actor direction (1 up,2 right,3 down,4 left) if changed, nonzero and not locked; flags anim change */
void     sub_0053_0e52(uint8_t *actor, int16_t state);  /* sets actor anim state (0 stand,4 walk,8 action) if changed and not locked; flags anim change */
int16_t  sub_0053_0e77(int16_t x1, int16_t y1, int16_t x2, int16_t y2);  /* returns direction 1..4 from (x1,y1) towards (x2,y2) (horizontal if |dx|/2 > |dy|) */
void     sub_0053_0ed4(uint8_t *actor);  /* turns actor towards its walk target (+0x32,+0x34) along the axis selected by flags&3 */
void     sub_0053_0f89(uint8_t *actor);  /* stops actor: clears walk flags (+0x30) and sets stand state */
void     sub_0053_0fa3(void);  /* player control from joystick/keys: turn, walk, action anim (8) */
void     sub_0053_1074(uint8_t *actor);  /* advances actor animation (applies pending state/dir anim change, steps frames, ends action anim) */
void     sub_0053_1192(void);  /* animates all living actors of the current room (sub_0053_1074) */
int16_t  sub_0053_11d5(int16_t room);  /* player touched door leading to room: requests room change (-1 = leave level); for side doors starts walk-off; returns 1 (0 if room==-1) */
void     sub_0053_1298(uint8_t *actor);  /* places actor at the door of the new room leading back to its old room; plays room scroll transition */
void     sub_0053_13cf(int16_t door, uint8_t *x1, uint8_t *y1, uint8_t *x2, uint8_t *y2);  /* gets door door's rectangle (x from door table 0x752, y from floor table), y1<=y2 */
void     sub_0053_1479(void);  /* performs pending room change (0xd0 -> 0xce): room script, obstacles, visit counter, player placement */
void     sub_0053_1568(void);  /* performs pending level change (0xa2): frees current level, loads new one, changes room */
void     sub_0053_1591(uint8_t *actor, uint8_t *px, uint8_t *py);  /* clamps new position (*px,*py) so the actor does not overshoot its walk target in its direction */
void     sub_0053_1678(int16_t dir, uint8_t *pdx, uint8_t *pdy);  /* adjusts step (*pdx,*pdy): vertical speed bonus 0xc4, room drift 0xb4/0xb6 by direction */
int16_t  sub_0053_16fa(int16_t idx);  /* moves walking actor idx one animation step with collision handling; returns 1 if moved, 0 if not walking/blocked */
int16_t  sub_0053_1831(int16_t x, int16_t y);  /* floor polyline: y of first point with px > x and py >= y, scanning forward (>=0xab -> 0xa0) */
int16_t  sub_0053_188d(int16_t x, int16_t y);  /* floor polyline: y of first point with px < x and py >= y, scanning backward (>=0xab -> 0xa0) */
void     sub_0053_18f4(int16_t idx, uint8_t *actor);  /* blocked by floor edge: re-targets actor walk around the floor contour */
void     sub_0053_19c1(int16_t idx, uint8_t *actor);  /* blocked by obstacle: re-targets actor walk randomly around obstacle bbox 0x3014..0x301a */
void     sub_0053_1a64(int16_t idx, uint8_t *actor);  /* chooses detour/stop for a blocked actor according to collision type +0x25 */
void     sub_0053_1adf(uint8_t *actor, int16_t idx, int16_t moved);  /* auto-walk logic after a step: detour if blocked, arrival/next waypoint, axis switch */
void     sub_0053_1b98(void);  /* moves all living actors of the room; sets enemy-present flags 0xae/0xf2 */
void     sub_0053_1c18(int16_t idx, int16_t x, int16_t y);  /* sets actor idx position and clears +0x28 and walk flags */
void     sub_0053_1c4e(void);  /* inserts all living actors of the room into the depth list (key = y, id = actor index) */
void     sub_0053_1c94(int16_t lang);  /* selects language: 0x10a = lang, first char of "T.CC4" = "TESDI"[lang] */
int16_t  sub_0053_1cb8(void);  /* returns 1 if the player may act (no menu, cutscene, input lock, auto-walk); may reset dialogue page 0x328a */
void     sub_0053_1cf8(void);  /* handles keyboard: key dispatch, pause 'P', music off ';'(AZERTY 'M'), Enter closes menu/dialogue (busy-waits on release) */
void     sub_0053_1daa(void);  /* reads input bits 0x2d4a into 0x327c, direction 0x3250 and fire 0x3030/0x3012 (masked by 0xc0 / menu) */
void     sub_0053_1deb(void);  /* menu cursor: up/down moves selection 0x3274 within 0..0x303a-1 */
void     sub_0053_1e2e(void);  /* frame limiter: adapts number of extra vsync waits 0x1736 from measured rate 0x2840 vs target 0xac, then waits */
void     sub_0053_1e8e(void);  /* one game-logic+render tick of a room (input, actors, depth list, draw, UI, present) */
void     sub_0053_1f21(void);  /* one main-loop frame: level/room changes, input, tick, dialogue, save/load request */
void     sub_0053_1f74(int16_t level);  /* plays one level (chapter) until 0xa2 == -1, then frees everything */
void     sub_0053_2014(void);  /* main(): hardware/driver init, launcher params, alloc, music, RNG seed, game init, intro level, world loop; never returns (sub_0791_0665 exits) */
void    sub_026c_0006(void);  /* marks all 16 projectile slots free (slot+0 = 0xff); called on room change */
int16_t sub_026c_0032(void);  /* returns index of first free projectile slot (byte +0 == 0xff), or -1 if none */
void    sub_026c_0067(int16_t owner);  /* spawns a projectile fired by character `owner` (char table 0x11a+owner*0x46): x=owner.x+rand(9)-8, y=owner.y, dir=owner.dir(+0x12), age=-1, +4=rand(128)+0x20; plays sound 0x31. No-op if no free slot */
void    sub_026c_010d(int16_t target, int16_t dir, int16_t damage);  /* projectile hit on character (target&0xf): if char.+0x14!=0 knock it back 0x20 px in dir (if new rect free of chars/obstacles); if char.+0x14==1 subtract `damage` from hp(+0x2a), start particle burst (fx mode [0x10c]=3) at (x,y-10) and play sound 0x32 */
void    sub_026c_0237(void);  /* per-frame projectile update: flying ones (age -1) move 15px horiz / 5px vert per dir, test hit vs characters (sub_0714_03d2) and walls (sub_0714_031f); on hit start impact (age 0) and call sub_026c_010d(hit,dir,1); impact frames count age 0..8 then slot freed */
void    sub_026c_034a(void);  /* inserts every active projectile into the depth-sorted draw list: sub_0053_075b(y, 0x20+slot) */
void    sub_026c_038b(void);  /* if player anim state (char0+0x0e,[0x128])==8 and anim frame (char0+0x1c,[0x136])==1: player fires (sub_026c_0067(0)) and plays sound 0x14 */
void    sub_02a7_0006(int16_t kind, int16_t item);  /* posts a status message: timer [0x104]=20, kind [0x106] (text 0x36+kind of table DSPTR(0x3290)), item [0x108] (item name appended if kind<4) */
void    sub_02a7_001d(int16_t x1, int16_t y1, int16_t x2, int16_t y2, int16_t color);  /* draws a bevelled box in the draw buffer: top/left lines col 0x9f, right/bottom 0x98, interior (x1+1,y1+1)-(x2-1,y2-1) filled with `color` */
void    sub_02a7_0098(void);  /* draws the current status message box (centred at x=160, y 0xa0..0xab, colour 0x9c) = message text [+ item name]; decrements timer [0x104] */
void    sub_02a7_0181(void);  /* inventory open: counts owned items into [0xbe], turns state 3 (just used) back into 2; if equipped item [0xba] no longer owned, picks next owned item; cursor [0xb8]=[0xba] */
void    sub_02a7_01e8(void);  /* draws the inventory list: up to 12 owned items from [0xbc] at x=0x1e, y=0x2c+10*k; colour 0x97, cursor item 0x9f + pointer glyph 0xc at (0xf,y+8), equipped item (state 2) 0x4d */
void    sub_02a7_02a9(void);  /* initialises the heartbeat (ECG) trace: [0x192a]=0, [0x1928]=rand(8)+1, 50 points at 0x30ae: x=0x109-i, y=0x14, dy=0, colour=0x7f-i/7 */
void    sub_02a7_0319(uint8_t *pt, int16_t x, int16_t y);  /* ECG helper: if x >= pt.x draws a line (x,y)-(pt.x,pt.y) in colour pt+6 */
void    sub_02a7_0351(uint8_t *pts);  /* ECG draw: restores column (head.x,4)-(head.x+1,0x24) on screen from back buffer, then draws the 50-point trail directly on the screen (shifting point history by one) and plots the head pixel in colour 0x9f */
void    sub_02a7_0410(void);  /* ECG step: beat state machine (delay [0x1928], phase [0x192a], amplitude [0x32ae]), head x += [0x32ac] wrapping 315->215, y += dy, then sub_02a7_0351 */
void    sub_02a7_04f1(void);  /* draws inventory-screen numbers with interface glyphs: play time [0x1fdc] as hhh mm ss (glyphs 0x17+d) and T%20 (glyphs 0x21+d), gold [0x11c6], completion % (sub_0c05_020c) */
void    sub_02a7_07c8(int16_t value, int16_t x, int16_t y);  /* draws `value` clamped 0..999 as 3 digit glyphs (0xd+digit, font DSPTR(0x3062)) at x, x+0x11, x+0x22 */
void    sub_02a7_0863(void);  /* redraws player HP box in the bottom bar: fill (0x106,0xb4)-(0x11c,0xbc) col 0x1d, HP [0x144] clamped 0..99 as 2 glyphs (0x2c+d) at y 0xbb; full-screen clip during, game-view clip after */
void    sub_02a7_08f3(void);  /* same as sub_02a7_0863 but draws directly into the screen buffer DSPTR(0x2d3c) */
void    sub_02a7_0920(void);  /* draws the inventory/status screen background (glyph 0xa), labels "Time","Name","gp","%","Don JONZ", then sub_02a7_04f1 (no own prologue; void) */
int16_t sub_02a7_09d0(void);  /* returns previous owned item index before cursor [0xb8], or [0xb8] if none */
int16_t sub_02a7_09fe(void);  /* returns next owned item index after cursor [0xb8] (<256), or [0xb8] if none */
void    sub_02a7_0a2d(void);  /* computes first visible inventory row [0xbc] = 5 owned items before the cursor (cursor unchanged) */
void    sub_02a7_0a5f(void);  /* inventory cursor up: [0xb8]=[0xbc]=previous owned item */
void    sub_02a7_0a6a(void);  /* inventory cursor down: [0xb8]=[0xbc]=next owned item */
int16_t sub_02a7_0a75(void);  /* inventory input: up/down move cursor; Enter or fire equips cursor item (old equipped -> state 1, new -> 2) and returns 1; Tab/Enter/Esc return 1; else 0 */
void    sub_02a7_0b4a(int16_t x1, int16_t y1, int16_t x2, int16_t y2);  /* copies rectangle (x1,y1)-(x2,y2) inclusive from draw buffer DSPTR(0x2d38) to the screen DSPTR(0x2d3c) (sub_103b_0004) */
void    sub_02a7_0b83(void);  /* blits the three dynamic areas of the inventory screen (time, gold, item list) to the screen */
void    sub_02a7_0bb5(void);  /* inventory/status screen main loop (action "I"): dissolve in, per-frame input/redraw/ECG, advances play time [0x1fdc] each frame, 'V' key shows version string; on exit restores palette DSPTR(0x3032) and game view */
void    sub_02a7_0c92(void);  /* while looking ([0x329a]!=0) draws a scan beam (sub_0dc5_058d, col 0x9f) from the player's head (offset by look dir [0x3060]) to target ([0x30a8],[0x323e]) jittered by rand(3)-1 */
void    sub_02a7_0d09(int16_t item, int16_t timer, uint8_t *texts);  /* shows description text #item of text table `texts` in the dialog box (sub_0596_0405); sets [0x3298]=0,[0x325e]=25,[0x326c]=item,[0x328a]=[0x32aa]=timer,[0x17bc]=1 */
void    sub_02a7_0d46(uint8_t *rect, int16_t widen, int16_t reach);  /* fills rect[4] (x1,y1,x2,y2 s16) with the zone in front of the player according to facing [0x12c], extended by `reach` (and `widen` sideways when facing up), clamped to 0..319 x 0..171 */
void    sub_02a7_0e21(void);  /* auto-look (every frame + action "L"): counts down/cancels active look [0x329a]; else, if player free, finds an undescribed hotspot in front (reach 0x32), marks it, starts 20-frame look and shows its description */
void    sub_02a7_0f54(void);  /* clears the "described" flag (+2) of every hotspot whose item is not owned */
void    sub_02a7_0f92(void);  /* action "T" (Take): picks up the hotspot item in front of the player: owns it, selects it, shows its text, message 2; message 4 if not takeable, 5 if nothing */
void    sub_02a7_1038(void);  /* action "S": sets flag [0x327a]=1 (talk/speak request handled by main loop) */
void    sub_02a7_103f(void);  /* action "I": opens the inventory screen (sub_02a7_0bb5) */
void    sub_02a7_1044(void);  /* action "L" (Look): resets hotspot flags, runs sub_02a7_0e21; message 6 if nothing found */
void    sub_02a7_1066(void);  /* action "U" (Use): marks the equipped item [0xba] as used (state 3) and posts message 3 */
void    sub_02a7_108d(void);  /* action "D" (Disk): calls the load/save menu sub_07fe_0ff1 */
void    sub_02a7_1093(void);  /* opens the action bar if actions are allowed (sub_0053_1cb8): state [0x3266]=1, bar y [0x17a8]=0xd4, cursor to pending action [0x17aa] or 0; else state 0, [0x17aa]=-1 */
void    sub_02a7_10df(void);  /* action bar state [0x3266]=0 (closed) */
void    sub_02a7_10e6(uint8_t key);  /* action bar key handler (scancode): T,U,L,S,I,D select action 0..5, Enter picks cursor action, Tab opens/closes (waits Tab release), Esc -> quit prompt sub_07fe_000e; applies pending action to the bar */
void    sub_02a7_11ed(void);  /* action bar cursor: slides [0x17a6] 2px/frame toward x of action [0x17b0] (table 0x179a); when there, joystick left/right changes [0x17b0] (0..5) */
void    sub_02a7_1264(void);  /* waits for vertical retrace (sub_118f_00de) then blits bottom panel (0,0xac)-(0x140,0xc7) to the screen */
void    sub_02a7_127c(void);  /* action bar modal loop: slide up, choose, flash, slide down, then calls action DSPTR(0x1782+4*[0x17aa]) */
void     sub_03dd_0008(uint8_t *filename, int16_t index, uint8_t *dest, int32_t size);  /* opens filename, reads long offset table, seeks to table[index], reads size bytes into dest, closes (PAK/CC4 entry loader) */
uint8_t *sub_03dd_00ac(int16_t actor);  /* returns pointer to actor struct DS:0x11a + actor*0x46 */
void     sub_03dd_00bc(uint16_t n);  /* inits script context n: start=IP=scriptbuf+wordtab[n], actor=0, flags=0x20 (stopped), +0xa=+0xc=0 */
void     sub_03dd_011f(void);  /* clears field +0x2a of actors 1..9 */
void     sub_03dd_014c(void);  /* resets script-driven room globals (effect mode, zone tables counts, control lock...) */
void     sub_03dd_017d(void);  /* sets script count [0xd8]=wordtab[0]/2, inits all contexts, enables script 0, frees temp buf, runs script 0 once */
void     sub_03dd_01c8(void);  /* loads room script (R??.CC4 entry [0xce]) into [0x177e] (0x898 bytes); fresh start -> 017d, savegame load -> sub_07fe_015c */
uint8_t  sub_03dd_01fb(void);  /* fetches next bytecode byte (IP++) */
uint16_t sub_03dd_0213(void);  /* fetches next bytecode byte and returns it *2 (X coordinate) */
int16_t  sub_03dd_022f(void);  /* fetches next bytecode 16-bit LE word (IP+=2) */
void     sub_03dd_024e(void);  /* skips one bytecode byte (IP++; used to consume the opcode) */
void     sub_03dd_0257(void);  /* relative jump: IP += (int16) word at IP (offset relative to the word itself) */
uint8_t  sub_03dd_026b(int16_t a, int16_t b, uint16_t op);  /* compare: op 0 ==,1 !=,2 >,3 >=,4 <,5 <=,6 a&b,7 a|b (signed); returns 1/0; op>7 -> 0 */
uint8_t *sub_03dd_02f0(int16_t var);  /* script variable address: var<0x46 -> DSPTR(0x166e+var*4); var<0x164 -> DS:0x11bc+(var-0x46)*2; else DS:0xfbc+(var-0x164)*2 */
int16_t  sub_03dd_034c(void);  /* fetches a variable index word from bytecode */
int16_t  sub_03dd_035b(void);  /* fetches a variable index word and returns that variable's value */
int16_t  sub_03dd_0380(void);  /* fetches tagged immediate: tag byte; tag==0x0c -> imm8 (zero-ext), else imm16 */
int16_t  sub_03dd_03da(void);  /* fetches operand: if byte at IP==0x0b -> skip it, variable value (035b); else immediate (0380) */
void     sub_03dd_0407(void);  /* op 0x53 / effect 1: [0x10c]=1 (transition mode 1); does NOT advance IP */
void     sub_03dd_040e(void);  /* op 0x56 / effect 4: [0x10c]=4, set palette #[0x3036] from palette bank (sub_0791_0187) */
void     sub_03dd_0420(void);  /* op 0x54 / effect 2: [0x10c]=2 */
void     sub_03dd_0427(void);  /* op 0x55 / effect 3: [0x10c]=3, sub_0791_020d([0x3036],[0x3038],50,500) (rect-list effect) */
void     sub_03dd_0443(void);  /* op 0x57 / effect 5: [0x17e2]=1 */
void     sub_03dd_044a(void);  /* op 0x58 / effect 6: sub_0596_02a0(0x49), draws "The End" at ([0x3036],[0x3038]) into draw buffer */
void     sub_03dd_0471(void);  /* op 0x20: var = operand          [20][var16][operand] */
void     sub_03dd_04a3(void);  /* op 0x21: var += operand */
void     sub_03dd_04d5(void);  /* op 0x38: var |= operand */
void     sub_03dd_0507(void);  /* op 0x39: var &= operand */
void     sub_03dd_0539(void);  /* op 0x22: var -= operand */
void     sub_03dd_056b(void);  /* op 0x23: own actor +0x25 = 8 */
void     sub_03dd_058b(void);  /* op 0x0a: IF  [0a][var16][cmpop8][operand][rel16]: if !(var cmp operand) jump else skip rel16 */
void     sub_03dd_05d4(void);  /* op 0x52 / effect 0: if [0x10c]==4 restore palette DSPTR(0x304c); [0x10c]=0 (also called from 014c) */
void     sub_03dd_05f2(void);  /* ops 0x0b,0x0c,0x0d,0x31: empty (operand tags, never executed; would not advance IP) */
void     sub_03dd_05f3(void);  /* op 0x00: [anim8] play animation on own actor once (+0x10=2), wait flag 0x04, yield */
void     sub_03dd_0643(void);  /* op 0x51: wait until mouse/keys released, then until key/mouse pressed (spins rand()) - BUSY WAIT */
void     sub_03dd_0679(void);  /* op 0x2d: [anim8][n8] own actor: +0x1a=anim,+0x20=0,+0x10=2,+0x22=n,+0x1c=n */
void     sub_03dd_06d1(void);  /* op 0x2e: [n8] play sound effect n (sub_0791_00e5) */
void     sub_03dd_06ee(void);  /* op 0x48: [n8] play music n (sub_0791_0078), 0xff = stop music */
void     sub_03dd_0717(void);  /* op 0x49: [v8] set music volume (sub_0791_0005) */
void     sub_03dd_0734(void);  /* op 0x4a: [n8] [0x304a] = random(n) (script var 41) */
void     sub_03dd_074a(void);  /* op 0x2f: [n8] [0x3268] = sprite bank parameter for next op 0x16 */
void     sub_03dd_0758(void);  /* op 0x33: [fx8][x2 byte][y8] [0x3036]=x,[0x3038]=y, call effect table DSPTR(0x1a8e+fx*4) */
void     sub_03dd_0787(void);  /* op 0x34: [v8] [0x177c]=v; if it went nonzero->0 set [0x1738]=1 */
void     sub_03dd_07b2(void);  /* op 0x35: choice menu: [q16][x2 byte][y8][n8] n*{[text16][rel16]} -> tables 0x306a, flag 0x10, yield */
void     sub_03dd_088c(void);  /* op 0x37: [0x173e]=1 */
void     sub_03dd_0897(void);  /* op 0x3a: [a8][b8] [0xbbc]=a,[0xbbe]=b, sub_0596_0001 (allocate work buffer) */
void     sub_03dd_08b3(void);  /* op 0x3b: [v8] byte [0xc4]=v */
void     sub_03dd_08bf(void);  /* op 0x32: no-op with 3 operand bytes (skips 4 bytes) */
void     sub_03dd_08d0(void);  /* op 0x30: own actor x=hero x, y=hero y+1 */
void     sub_03dd_0915(void);  /* op 0x01: [dir8] own actor +0x10=0, set facing dir (sub_0053_0e27) */
void     sub_03dd_0956(void);  /* op 0x15: own actor faces the hero (dir from sub_0053_0e77) */
void     sub_03dd_09b7(void);  /* op 0x17: [n8] n*{[x2 byte][y8]} -> word list at 0x1832 (count,x,y..), sub_0053_0cc4 (walk polygon) */
void     sub_03dd_0a13(void);  /* op 0x18: [n8] n*{[b8][b8][x2 byte][x2 byte]} -> 6-byte entries at 0x752, [0xa8]=n */
void     sub_03dd_0a77(void);  /* op 0x19: [mode8] 5 words (b,b,b,x2,b) (+5 more if mode==2) -> 0xbc0, [0xc6]=mode */
void     sub_03dd_0b3c(int16_t wide);  /* helper for 0x1a/0x4f: append entry to 0xa18[[0xf0]++]: id(byte or word if wide),0,wide,x2 byte,byte */
void     sub_03dd_0ba9(void);  /* op 0x1a: sub_03dd_0b3c(0) */
void     sub_03dd_0bb2(void);  /* op 0x4f: sub_03dd_0b3c(1) */
int16_t  sub_03dd_0bbb(void);  /* returns 1 if the next opcode is 0x1f (animation) or 0x51 (wait key); used by sub_0596_0f41 to skip the room redraw */
void     sub_03dd_0bf5(void);  /* op 0x1f: PAK animation: [pak8][seq8][bg16][reps8][n8] n*3-byte sound cues; [0x328c]=n, DSPTR(0x32a2)=cues, sub_0596_0f41(pak,seq,bg,reps) */
void     sub_03dd_0c5b(void);  /* op 0x29: if own actor!=0: +0x2a=0 and release its sprite (sub_0053_01e8) if loaded */
void     sub_03dd_0ca5(void);  /* op 0x2a: [x2 byte][x2 byte] own actor +0x3c,+0x3e */
void     sub_03dd_0cdd(void);  /* op 0x2b: [a8][b8] own actor bytes +0x40,+0x41 */
void     sub_03dd_0d15(void);  /* op 0x2c: [v8] [0xd0]=v (0xff -> -1) */
void     sub_03dd_0d3a(void);  /* op 0x4b: [room8] [0xa2]=[0x32a6]=room (request room change) */
void     sub_03dd_0d4b(void);  /* op 0x1b: copy-protection question (sub_0c05_00fc) */
void     sub_03dd_0d55(void);  /* op 0x02: stop this script (flag 0x20), yield (IP not advanced) */
void     sub_03dd_0d65(void);  /* op 0x1c: [n8] if n<[0xd8]: restart script n and enable it */
void     sub_03dd_0d9c(void);  /* op 0x1d: [n8] stop script n (flag 0x20), no bounds check */
void     sub_03dd_0dc3(void);  /* op 0x1e: list of bytes until 0xff: restart+enable each script */
void     sub_03dd_0e01(void);  /* op 0x03: GOTO [rel16] */
void     sub_03dd_0e0a(void);  /* op 0x43: ctx loop counter (+0xc)=0, then GOTO */
void     sub_03dd_0e19(void);  /* op 0x24: [x2 byte][y8] own actor walks to (x,y), wait flag 0x01, yield */
void     sub_03dd_0e78(int16_t vert);  /* helper for 0x04/0x05: [c8][anim8] walk own actor to x=c*2 (vert=0) or y=c (vert=1), wait 0x01, yield */
void     sub_03dd_0f38(void);  /* op 0x04: sub_03dd_0e78(0) walk horizontally */
void     sub_03dd_0f41(void);  /* op 0x05: sub_03dd_0e78(1) walk vertically */
void     sub_03dd_0f4a(int16_t vert);  /* helper for 0x0f/0x10: [anim8] walk own actor to hero x (vert=0) or hero y (vert=1), wait 0x01, yield */
void     sub_03dd_0ffd(void);  /* op 0x0f: sub_03dd_0f4a(0) */
void     sub_03dd_1006(void);  /* op 0x10: sub_03dd_0f4a(1) */
void     sub_03dd_100f(void);  /* op 0x11: [dx s8][dy s8] walk own actor to hero pos+(dx,dy) (clipped by sub_0714_0160), +0x28=6, wait 0x01, yield */
void     sub_03dd_10ab(void);  /* op 0x42: own actor stance 8 (sub_0053_0e52), +0x14=1 */
void     sub_03dd_10e1(void);  /* op 0x45: [v8] own actor +0x14=v */
void     sub_03dd_110e(void);  /* op 0x4c: [x2 byte][y8][x2 byte][y8] [0xdc]=1,[0xde]=x1,[0xe2]=y1,[0xe0]=x2,[0xe4]=y2 */
void     sub_03dd_1139(void);  /* op 0x46: [v8] [0xac]=v */
void     sub_03dd_1147(int16_t param);  /* switch to special scene 8: [0xa2]=[0x32a6]=8, [0xd0]=[0x329e]=0, var[0x11c4]=param, [0xc0]=0xf, hero dir=1 */
void     sub_03dd_116f(void);  /* op 0x47: [p8] sub_03dd_1147(p), [0x173e]=1, yield */
void     sub_03dd_1197(void);  /* op 0x06: LOOP [rel16][count8]: ++ctx+0xc < count -> jump; else counter=0, skip 3 */
void     sub_03dd_11da(void);  /* op 0x07: [x2 byte][y8] place own actor at (x,y) (sub_0053_1c18) */
void     sub_03dd_120c(void);  /* op 0x08: [n8] sync with script n: ctx+0xa=n, flag 0x08, yield */
void     sub_03dd_122a(void);  /* op 0x0e: IF hero in zone [x2 byte][y8][x2 byte][y8][rel16] (zone saved in ctx+0xe..0x14), else jump */
void     sub_03dd_1331(void);  /* op 0x3d: if [0x327a]: clear it, skip rel16; else jump */
void     sub_03dd_1352(void);  /* op 0x3e: [x2 byte][y8][x2 byte][y8] append rect to 0x30ae[[0x1740]++] (stored x1,y1,y2,x2) */
void     sub_03dd_13a6(void);  /* op 0x44: [x2 byte][y8][x2 byte][y8] [0x32a0]=1, [0x3020..0x3026]=x1,y1,x2,y2 */
void     sub_03dd_13d1(void);  /* op 0x3c: 4 bytes appended to 4-byte table 0x1286[[0x1284]++] */
void     sub_03dd_1434(void);  /* op 0x3f: [a8][b8] for each 0x1286 entry with e[0]==a && e[1]==b: e[2]=e[0] */
uint8_t  sub_03dd_14a2(int16_t x1, int16_t y1, int16_t x2, int16_t y2);  /* returns 1 if hero bounding box overlaps rect (sub_0e9b_000c) */
void     sub_03dd_156c(void);  /* op 0x27: wait while hero is inside the zone saved in ctx (yield w/o advancing), else IP++ */
void     sub_03dd_1598(void);  /* op 0x28: [zone 4 bytes] saves zone; if hero not inside: IP-=5 and yield (wait for hero to enter) */
void     sub_03dd_1608(void);  /* op 0x12: [b8] b==0: [0x3250]=0,[0xc0]=0xf; else [0xc0] |= word table DS:0x1aaa[b] (player control lock) */
void     sub_03dd_1640(void);  /* [0xc0]=0 (unlock); if hero +0x10==2 set it to 0 */
void     sub_03dd_1654(void);  /* op 0x13: sub_03dd_1640 */
uint8_t *sub_03dd_165d(int16_t idx, uint8_t *text);  /* text bank lookup: finds the idx-th '*' (0-based) and returns pointer just past the following NUL */
void     sub_03dd_169e(int16_t actor, int16_t textidx, int16_t color);  /* shows speech text textidx of bank DSPTR(0x325a) for actor; [0x17bc]=1, [0x325e]=color */
void     sub_03dd_16d3(void);  /* op 0x40: [c8] own actor +0x2c = text colour */
void     sub_03dd_16f8(int16_t actor, int16_t textidx, int16_t anim);  /* actor says text, plays talk anim (0xff=none) saving old anim in [0x9a]/[0x32a8]/[0x329c]; wait flag 0x40, yield */
void     sub_03dd_1775(void);  /* op 0x14: SAY [text16][anim8] by own actor */
void     sub_03dd_17a6(void);  /* op 0x4e: [0x17ac]=1 (end/quit request), yield */
void     sub_03dd_17b7(void);  /* op 0x4d: SAY [actor8][text16][anim8] */
void     sub_03dd_17ea(void);  /* op 0x36: [text16][t8] show text by own actor without waiting; [0x328a]=[0x32aa]=t */
void     sub_03dd_1843(void);  /* op 0x41: [v8] [0x9c]=v */
void     sub_03dd_1851(void);  /* op 0x26: [v8] if [0xa0]==0: [0xd4]=v>>4; [0xd2]=(v&15)+1 */
void     sub_03dd_187e(void);  /* wait handler flag 0x08: if partner script ctx[+0xa] also waits (flag 8) for us, clear both; else yield */
void     sub_03dd_18d7(void);  /* op 0x09: [n8] WAIT n ticks: ctx+0xa=n, flag 0x02, yield */
void     sub_03dd_18f5(void);  /* op 0x50: [n8] set game flag bit n (sub_0c05_01ea) */
void     sub_03dd_1908(void);  /* op 0x16: [a8][spr8] bind script to actor a; a!=0: load sprite (bank [0x3268],spr) and init actor; a==0: hero colour 0x19; [0x3268]=0 */
void     sub_03dd_1969(void);  /* op 0x25: [0xee]=1, [0xd2]=0 */
void     sub_03dd_1979(void);  /* wait handler flag 0x04: clears flag when own actor frame +0x1c == +0x20-1, else yield */
void     sub_03dd_19b8(void);  /* wait handler flag 0x01: clears flag when own actor stopped walking ((+0x30&3)==0 or +0x2a==0), else yield */
void     sub_03dd_19fb(void);  /* wait handler flag 0x02: decrements ctx+0xa; clears flag at 0, else yield */
void     sub_03dd_1a23(void);  /* wait handler flag 0x40: when text finished ([0x17bc]==0) clear flag, restore saved talk anim; else yield */
void     sub_03dd_1a7f(void);  /* wait handler flag 0x10: when menu done ([0x3240]==0) IP = chosen entry ptr (0x306a[[0x3274]]+6), relative jump; else yield */
void     sub_03dd_1ac0(uint16_t n);  /* runs script n for one tick: sets ctx, runs wait handlers, then dispatches opcodes via 0x1946 until [0x328e] (yield) */
void     sub_03dd_1b6d(void);  /* runs scripts 1..[0xd8]-1 for one tick (per-frame call from sub_0053_1e8e) */
void     sub_0596_0001(void);  /* ensures the 0xFFFF-byte backdrop buffer DSPTR(0x17b4) is allocated: if NULL, flush resource cache (sub_0053_028e) when farcoreleft (sub_0791_05f7) < 0xFFFF, then DSPTR(0x17b4)=farmalloc(0xFFFFL) */
void     sub_0596_0033(void);  /* frees the backdrop buffer DSPTR(0x17b4) (farfree) if non-NULL and sets it NULL */
void     sub_0596_0059(void);  /* per-frame FX+present: fx 1 = redraw hero reflection (actor 1 at 0x160 with hero's anim/frame) clipped into two window rects when hero x>0xa0,y<0x88; fx 3 = count down [0x3260] (0 -> fx off) else particles (0791_025b); lightning/sprinkle/panel-refresh hooks; frame limiter; then present: dirty rect [0xde..0xe4] via 02a7_0b4a, else by zoom [0x177c] 0=plain copy,1/2/3=2x/3x/4x zoom around hero; room 0x17 palette pulse (0..15) when [0x11c0]==1 && [0xa0]==3 */
void     sub_0596_02a0(int16_t color);  /* selects the game font DSPTR(0x3042) and text colour `color` (sub_1172_011d) */
void     sub_0596_02b7(int16_t x1, int16_t y1, int16_t x2, int16_t y2);  /* sets the drawing clip rectangle: xmin=x1,xmax=x2 (ss:0x196/0x198), ymin=y1,ymax=y2 (ss:0x192/0x194) */
void     sub_0596_02d6(void);  /* clip rectangle = play area: (0, [0x303c]) - (319, [0x3054]-1) */
void     sub_0596_02ec(void);  /* clip rectangle = full screen (0,0)-(319,199) */
void     sub_0596_02fe(uint8_t *str, int16_t x, int16_t y, int16_t color);  /* draws NUL-terminated string at (x,y) into the draw buffer DSPTR(0x2d38) in colour `color` using the game font */
uint8_t *sub_0596_0327(uint8_t *str);  /* returns pointer just past the terminating NUL of str (start of the next sub-string) */
int16_t  sub_0596_033e(uint8_t *text, int16_t x, int16_t y, int16_t color, int16_t mode);  /* draws up to 3 NUL-separated lines of a '*'-terminated text block, 10 px apart, y clamped >= [0x303c]+3; mode 0 = each line centred on x (kept within 3..0x13c, empty lines skipped), else left-aligned at x (see notes: uninitialised local => every line drawn); returns y below last line */
void     sub_0596_0405(uint8_t *text);  /* measures one page (<=3 lines) of a '*'-terminated text block: DSPTR(0x3242)=text, [0x30aa]=max width/2, [0x30ac]=10*non-empty lines, [0x328a]=[0x32aa]=display time (sum width/4), [0x17be]=1 if another page follows, DSPTR(0x3028)=next page */
void     sub_0596_04b7(int16_t x1, int16_t y1, int16_t x2, int16_t y2);  /* draws a speech-bubble frame: rect shifted to stay on screen/in play area, interior filled col 0x1a, double border lines cols 0x43/0x45, corner sprites 0..3 of bank DSPTR(0x3066) */
void     sub_0596_067e(void);  /* ends speech display: [0x17bc]=0 (speech active), [0x9c]=0 (bubble y override) */
void     sub_0596_0687(void);  /* per-frame speech bubble: if speaking and speaker actor [0x3298] is in current room [0xce], draws bubble+centred text DSPTR(0x3242) (colour [0x325e]) above it (x=0xa0 if [0xa0]==8, y=[0x9c] if set); counts down [0x328a], then shows next page (0405) or ends speech (067e) */
void     sub_0596_0767(void);  /* draws the dialogue choice menu at ([0x302c],[0x302e]): optional question DSPTR(0x3252) (if [0x3278]!=-1) then [0x303a] answers from table 0x306a (10-byte entries, text fptr +2), each in its own bubble; selected [0x3274] highlighted (colour cycle 0x16..0x19 via [0x17b8]/[0x17ba] if hero text colour [0x146]==0x19, else blink with [0x1896]&1 / col 0x9f) */
void     sub_0596_08e0(int16_t i);  /* draws projectile slot i (table 0x692, 12 bytes): if used (+0!=0xff): age(+2)==-1 -> packed image 0 of entry 1 of DSPTR(0x3262) at (+6,+8-25); else impact frame `age` of bank DSPTR(0x3262) at (+6,+8) with param +4 (sub_106a_04ff) */
void     sub_0596_0965(int16_t dir);  /* horizontal room-scroll transition: copies screen DSPTR(0x2d3c) to draw buffer, then 8 steps of 40 px: shifts play area by 40 px (dir==-1: image moves left, new room strip enters at the right edge; else moves right, strip enters at left) pulling the strip of the new room from DSPTR(0x3056), presenting each step (0dc5_0148) with pause check */
void     sub_0596_09d5(void);  /* room-scroll transition, new room enters from the right: sub_0596_0965(-1) */
void     sub_0596_09de(void);  /* room-scroll transition, new room enters from the left: sub_0596_0965(0) */
void     sub_0596_09e7(uint8_t *actor, int16_t x1, int16_t y1, int16_t x2, int16_t y2);  /* fx 2 mirror: if actor x within [x1-16,x2+16] and actor y >= y2, draws actor's mirrored image (reversed facing if +0x0e==4) at (x-3,y-8) clipped to (x1,y1)-(x2,y2); sprite from anim frames (kind +0x12 2/4) or dir tables 0x1820 (kind 1)/0x180e; restores play-area clip */
uint8_t *sub_0596_0b11(int16_t seq, uint8_t *res);  /* returns animation sequence `seq` of a PAK resource: sub-entry seq of entry 2 (sub_0053_0564(2,seq,res)); byte +1 = frame count, frames (8 bytes each) start at +2 */
int16_t  sub_0596_0b28(uint8_t *bank, uint8_t *frames, int16_t idx, int16_t step, int16_t x, int16_t y, int16_t nframes);  /* draws frame idx of an animation at (x,y)+sum of frame dx/dy 0..idx; frame type (word+2 bits 14-15): 0 plain, 2 sprite w/ param (106a_04ff), 3 shaded (106a_0593), 1 morph toward next frame over `param` steps using work buffer DSPTR(0x3294): returns next step (0 when done), other types return 0 */
void     sub_0596_0cca(int16_t i);  /* draws actor i (0x11a+i*0x46) clipped to its rect (+0x3c,+0x40b)-(+0x3e,+0x41b): fx 2 mirror image, then morph anim (+0x10==2, stores step in +0x1e) or frame +0x1c of sequence +0x1a; hero extras: look beam (02a7_0c92) and sparkle (0791_0506) if [0x11be]; restores play-area clip */
void     sub_0596_0e28(void);  /* draws action-bar cursor: state [0x3266]==3 (flash) -> glyph [0x17b0]+2 and 1 at (0,0) and glyph 9 at ([0x17a6],[0x17a8]); else glyph 8 at ([0x17a6],[0x17a8]); bank DSPTR(0x3062) */
void     sub_0596_0e96(void);  /* draws bottom panel background: glyphs 0 and 1 of bank DSPTR(0x3062) at (0,0) */
void     sub_0596_0ec3(void);  /* redraws bottom panel: [0x1738]=0, full clip, 0e96, copies rect (0,0xac)-(0x140,0xc7) to screen, 02a7_08f3 (panel contents on screen), play-area clip */
void     sub_0596_0eee(void);  /* clears play area of draw buffer: fill (0,0)-(0x140,0xab) colour 0 */
void     sub_0596_0f03(void);  /* dead (unreferenced): calls sub_0596_0e96() */
void     sub_0596_0f08(void);  /* dead (unreferenced): full clip; draws bottom panel directly on screen (DSPTR(0x2d38) temporarily = DSPTR(0x2d3c)) and again in the draw buffer; play-area clip */
void     sub_0596_0f41(int16_t pak, int16_t seq, int16_t bg, int16_t reps);  /* plays animation seq of A??.PAK entry `pak` (DSPTR(0x18a0)) `reps` times over background bg (0 black, <0 sprite -bg of the anim, <0x7d00 room sprite bg, ==0x7d00 current screen); per frame: restore bg from 0x3056, draw (0b28), speech (0687), palette (entry 4) on first frame, present, sound cues from DSPTR(0x32a2) ([0x328c] triples frame/sfx/-); Enter skips, Esc -> sub_07fe_000e; frees anim, restores palette, redraws room unless next script op is another animation */
void     sub_0596_11cf(int16_t x1, int16_t y1, int16_t x2, int16_t y2, int16_t n);  /* draws n random sparkles (packed image 0x67+rand(2) of entry 1 of room pack DSPTR(0x3286)) at random points in (x1,y1)-(x2,y2) */
void     sub_0596_1252(void);  /* draws room contents in depth order from draw list DSPTR(0x3270) (count byte +0, 2-byte records from +3: hi nibble 0=actor 0cca, 2=projectile 08e0, 1=next room foreground piece from sub-entry [0xce]*2+1 of DSPTR(0x3286)); room 0x13 sparkles; look beam; exit markers (171e) */
void     sub_0596_13bb(int16_t room, int16_t slot);  /* draws backdrop layer `slot` of table 0xbbc (if pak idx [0xbbc+slot*2]>0: load D??.PAK entry into DSPTR(0x17b4), install its palette (entry 4) if present, draw sprite [0xbbe+slot*2]) then room background sprite room*2 of DSPTR(0x3286) (clearing rows 0..0x12 if [0xa0]==0); [0xa0]==0x63: copy DSPTR(0x34c2) to draw buffer + sub_0a86_0325 instead */
void     sub_0596_14c9(int16_t room);  /* sub_0596_13bb(room, 0) */
void     sub_0596_14d9(int16_t room);  /* draws room foreground sprite room*2+1 of DSPTR(0x3286) at (0,0) if it is a real sprite (byte +1 != 0) */
void     sub_0596_1543(int16_t room, int16_t slot);  /* clears draw buffer, draws room background with backdrop slot (13bb) and foreground (14d9) */
void     sub_0596_1564(void);  /* builds parallax background in DSPTR(0x3056): copies draw buffer there, renders room [0xbc0] (backdrop slot 3); if [0xc6]==2 blits it 1/4-scaled at ([0xbc6],[0xbc8]) then renders room [0xbca] (slot 8) and uses ([0xbd0],[0xbd2]); finally blits the last rendered room 1/2-scaled at that position (colour 0 transparent) and clears the draw buffer */
void     sub_0596_1614(void);  /* if sub-palette byte [0xd4] != [0xd3]: [0xd3]=[0xd4], copies 16 colours (48 bytes) from DSPTR(0x301c)+idx*48 into palettes DSPTR(0x3032) and DSPTR(0x304c) at colour 0xa0, and uploads them to the DAC (118f_01ab) */
void     sub_0596_169f(void);  /* full room background rebuild: clear, parallax (1564 if [0xc6]), room bg/fg for [0xce], bottom panel, then stores result in DSPTR(0x3056) (transparent overlay if [0xc6]), colour-0xf gradient effect if [0xee], sub_0a86_0000, sub-palette update (1614) */
void     sub_0596_171e(void);  /* draws exit markers: for each zone in table 0x752 (count [0xa8]) with type 3, two lines col 1 on rows 0xaa/0xab from x(+2) to x(+4) and small col-9 boxes at both ends */
void     sub_0596_17cd(void);  /* blanks the play area: clears it in the draw buffer (0eee) and copies (0,0)-(0x140,0xab) to screen */
int16_t sub_0714_0004(int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void sub_0714_002e(uint8_t *px, uint8_t *py, int16_t halfw, int16_t height);
void sub_0714_0160(uint8_t *px, uint8_t *py, int16_t halfw, int16_t height);
void sub_0714_0210(uint8_t *actor);
void sub_0714_023e(int16_t actor_idx, int16_t tx, int16_t ty);
int16_t sub_0714_031f(uint8_t *rect, int16_t dir);
int16_t sub_0714_03d2(int16_t self_idx, uint8_t *rect);
int16_t sub_0714_04a0(uint8_t *rect);
int16_t sub_0714_0559(uint8_t *rect);
int16_t sub_0714_05e4(uint8_t *rect, int16_t dir);
int16_t sub_0714_06c7(int16_t actor_idx, int16_t x, int16_t y, int16_t halfw, int16_t height, int16_t dir);
int16_t sub_0714_075b(uint8_t *actor, int16_t actor_idx, int16_t code);
void sub_0791_0005(int16_t vol);
void sub_0791_0039(void);
void sub_0791_0048(int16_t n);
void sub_0791_0078(int16_t n);
void sub_0791_00e5(int16_t n);
void sub_0791_0132(int16_t n);
void sub_0791_0178(void);
void sub_0791_0187(int16_t level);
void sub_0791_01b7(uint8_t *part);
void sub_0791_020d(int16_t x, int16_t y, int16_t count, int16_t duration);
void sub_0791_025b(void);
void sub_0791_034e(int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void sub_0791_040c(void);
void sub_0791_0506(int16_t x1, int16_t y1, int16_t x2, int16_t y2);
void sub_0791_05d9(void);
int32_t sub_0791_05f7(void);
void sub_0791_0604(void);
void sub_0791_0638(uint8_t *actor, int16_t damage);
void sub_0791_0665(void);
void sub_0791_067f(uint8_t *pal);
void sub_0a21_0005(int16_t frameA, int16_t xA, int16_t yA, uint8_t *shapeA, int16_t frameB, int16_t xB, int16_t yB, uint8_t *shapeB, uint8_t *out);
void    sub_07fe_000e(void);  /* "Quit game?" box drawn directly on screen (msg #0x36 of text DSPTR(0x3290)); waits for a key, on Y/O/J/S scancode (0x15/0x18/0x24/0x1f) calls sub_0791_0665 (exit to DOS) */
int16_t sub_07fe_00b2(uint8_t *filename);  /* file-open error handler (installed in fnptr DSPTR(0x2d40), called by fopen sub_0e66_0031): box + msg #0x37 + filename, waits key, Esc -> sub_07fe_000e; always returns 1 (= retry) */
void    sub_07fe_015c(void);  /* after a savegame load: rebases the anim table at DS 0x7b2 (DSU16(0xd8) entries x 0x16 bytes): +0 = anim base (from offset table at start of resource DSPTR(0x177e)), +4 = +0 + (uint16)(old+4 - old+0) */
void    sub_07fe_01d5(uint8_t *oldptr, uint8_t *newptr);  /* replaces sprite pointer +0x16 of actors (DS 0x11a, 10 x 0x46) equal to oldptr by newptr, at most once per actor (flags u8[10] at DS 0x32b4) */
void    sub_07fe_0231(void);  /* re-links the resource cache DS 0x928 (20 x 6 bytes): reloads every PAK entry (kind 0, ptr!=NULL) from PAK name DSPTR(0x18a0), else takes fixed resource sub_0053_03a5(kind); patches actor pointers via sub_07fe_01d5 */
void    sub_07fe_02df(void);  /* out-of-memory fallback (called by sub_0053_0413): farfree every cached PAK resource of table DS 0x928 then reload all with sub_07fe_0231 (heap defragmentation) */
void    sub_07fe_032a(uint8_t *buf, int16_t len);  /* savegame (de)obfuscation: buf[i] ^= (uint8_t)(5 + 5*i) for i < len (symmetric) */
void    sub_07fe_035d(void);  /* applies the loaded save: copies savebuf(DSPTR(0x3294))+0x3e6 -> DS 0x9e..0x166b (0x15ce bytes), restarts music track DS16(0xd6) (sub_0791_0078) */
int16_t sub_07fe_03ab(int16_t slot);  /* loads "<slot>.AVE" into DSPTR(0x3294), checks 16-bit byte sum, decrypts, restores DS 0x1fba block and schedules/does the state switch depending on room DS16(0xa0) now/in save; returns 1 if the checksum was OK, 0 if open failed; bad checksum -> error box loop (sub_07fe_00b2 always 1: never returns) */
int16_t sub_07fe_057e(int16_t slot);  /* saves "<slot>.AVE": purge cache, build 8000-byte image in DSPTR(0x3294) (name[40], DS 0x1fba[0x3e], DS 0x9e[0x15ce]), encrypt, write 0x1f3e bytes + 2-byte checksum; returns 1 on success, 0 if create failed; clears DS16(0x98) */
void    sub_07fe_06de(int16_t x1, int16_t y1, int16_t x2, int16_t y2, int16_t color);  /* draws a bevelled box (lines 0x97/0x9f/0x9a/0x9e/0x99) filled with color into the draw buffer */
void    sub_07fe_0847(void);  /* reads the 40-byte name header of 0.AVE..9.AVE into the slot table DSPTR(0x32be) (10 x 40); missing file -> name[0]=0xff; disables the fopen error handler DSPTR(0x2d40) meanwhile and reinstalls sub_07fe_00b2 */
void    sub_07fe_08d2(int16_t slot, int16_t editing);  /* draws one save-slot row (y = slot*14+18): number box, name box (highlight if slot==DS16(0x1af2)), slot number, name; if editing && selected draws the text cursor after the name */
void    sub_07fe_09dc(int16_t mode);  /* sets text colour 0 and draws slot rows mode..9 (save mode 1 hides slot 0) with editing=mode */
int16_t sub_07fe_0a0b(int16_t mode);  /* edits the name of the selected slot (AZERTY scancode table DS 0x1afe, max 38 chars / 220 px, backspace); returns 2 on Enter, 1 on Esc or up/down (up/down restore the old name) */
void    sub_07fe_0bd5(int16_t mode);  /* save/load slot menu (mode 0 = load, 1 = save): slot table is a 400-byte local published in DSPTR(0x32be); up/down select DS16(0x1af2), Enter/typing confirm, Esc allowed only if hero HP DS16(0x144) > 0 */
void    sub_07fe_0d4c(int16_t x, int16_t filled);  /* draws one 5-pixel volume gauge tick at column x, rows 188..192 (colours 0x33.. if filled else 0x92..) */
void    sub_07fe_0de3(void);  /* redraws the options panel (bank DSPTR(0x32b0)): background, selected item box, 5 labels (LOAD/SAVE/Music/Sound/Window), music/sound gauges (DS16(0xe8)/8, DS16(0xea)/8), window-size marker DS16(0xe6); presents bottom panel */
void    sub_07fe_0f88(void);  /* if in 3D outdoor mode (DS16(0xa0)==-1) and window size DS16(0xe6)!=2: clears the 3D view area on screen (sky gradient 100 rows + ground colour 0x55 rows 100..171) */
void    sub_07fe_0fdc(void);  /* after a window-size change in 3D mode: sub_07fe_0f88 + re-render view sub_0a86_0d96(0) */
void    sub_07fe_0ff1(void);  /* options panel main loop (loads "a99" #0x37, slides it in/out): Load/Save (-> sub_07fe_0bd5), music/sound volume 0..15, 3D window size 0..2; keys Esc/Enter/L/S */
void    sub_0c05_0009(int16_t value, int16_t ref);  /* draws the copy-protection box: "Reference :" day string DSPTR(0x22fe+(ref/12)*4), month DSPTR(0x22ce+(ref%12)*4), and the 3-digit entered value; flips to screen */
void    sub_0c05_00fc(void);  /* copy protection: picks ref = random(192), answer = word[ref] of PAK "intro" entry 2, reads a 3-digit code (digit keys, Enter ends), sets DS16(0x11c8) = (code == answer) */
void    sub_0c05_01ea(int16_t n);  /* sets bit n in the flag bitfield u8[13] at DS 0xf6 (script opcode) */
int16_t sub_0c05_020c(void);  /* returns the number of set bits in the flag bitfield DS 0xf6[0..12] (shown as a 2-digit counter in the status panel) */
void    sub_0c05_0254(int16_t x, int16_t y, int16_t heading, int16_t overlay);  /* 3D mode: moves the camera (DS 0x1fc2 x, 0x1fc4 y, s8 0x1fcd heading) linearly to x,y,heading in max(dist/40,|dh|) rendered steps; overlay!=0 draws sprite 0 of DSPTR(0x34ce); decelerates DS16(0x1fc6) */
void    sub_0c05_036f(void);  /* scripted 3D flight: loads PAK "i2" #0xc into DSPTR(0x34ce), music 0x24, camera at (0xd00,0x1d63,-4), follows 7 waypoints of DS 0x22a4 (x,y,heading), frees, stops music */
void    sub_0c05_0400(void);  /* 3D mode door check: if camera cell (x/512,y/512) and zone DS16(0x1fd6) match an entry of DS 0x21a4 (20 x {zone,x,y,?}) sets next room DS16(0xa2)=index; special doors DS 0x2244 (3 entries) -> DS 0x2286/0x11bc/0xa2=3/0x329e=7 */
void    sub_0c05_0511(void);  /* 3D zone change: resets objects (sub_03dd_011f, sub_0053_0112) and spawns up to 8 zone objects from list table DS 0x1bbc (lists zone*8+i) via sub_0936_0106; DS16(0x1fd8) = DS16(0x1fd6) */
void    sub_0c05_056b(void);  /* 3D random encounter: spawns list zone*16+DS16(0x1fda)+0x28 of DS 0x1bbc at its x,y (words +4,+5) jittered by random(501)-250, then restores the table */
int16_t sub_0936_0005(int16_t path_no);
void sub_0936_0053(uint8_t *actor);
int16_t sub_0936_00d1(void);
void sub_0936_0106(int16_t path_no, int16_t slot);
uint8_t sub_0936_0225(int16_t x0, int16_t y0, int16_t x1, int16_t y1);
void sub_0936_029e(uint8_t *actor);
void sub_0936_04af(void);
void sub_0936_04f4(void);
void sub_0936_056e(uint8_t *actor, int16_t sx, int16_t sy, int16_t scale, int16_t ground_y, int16_t size);
void sub_0936_0855(int16_t sx, int16_t sy, int16_t size);
void sub_0936_0876(int16_t sx, int16_t depth, int16_t sy, int16_t id);
void sub_0936_0948(void);
void sub_0936_0985(void);
void sub_0936_09b1(void);
void sub_0936_0a73(void);
void sub_0936_0b5f(void);
void sub_0936_0ba4(int16_t x0, int16_t y0, int16_t x1, int16_t y1);
void sub_0936_0bec(void);
void sub_0936_0c14(void);
void sub_0936_0c5e(int16_t id, int16_t type);
void sub_0936_0c9f(void);
void sub_0936_0d18(void);
void sub_0936_0dc0(void);
void sub_0936_0df4(void);
void sub_0936_0e23(void);
void sub_0936_0e2d(void);
uint8_t *sub_0c66_0003(uint8_t *name, int16_t index);
void sub_0c9b_0022(uint8_t *src_pal, uint8_t *dst_pal, uint16_t level);
void sub_0c9b_005c(uint8_t *src_rgb, uint8_t *dst_pal);
int16_t sub_0c9b_00d8(int16_t a, int16_t b, int16_t num, int16_t den);
void sub_0c9b_00fe(uint8_t *hmap, uint8_t *tile);
void sub_0c9b_01cd(uint8_t *verts, uint8_t *edges);
void sub_0c9b_024e(void);
void sub_0c9b_0293(void);
void sub_0c9b_02b6(void);
int16_t sub_0c9b_0323(int16_t x, int16_t y, int16_t tile);
void sub_0c9b_03e5(void);
void sub_0c9b_0404(void);
void sub_0c9b_0464(void);
void sub_0c9b_04a1(void);
void sub_0c9b_04cc(void);
void sub_0c9b_04f4(uint8_t *src, uint8_t *dst, int16_t camx, int16_t camy, int16_t mode);
void sub_0c9b_05b2(uint8_t *def, uint8_t *dst);
void sub_0c9b_06a4(void);
void sub_0c9b_06fe(void);
void sub_0c9b_0744(uint8_t *src);
void sub_0c9b_077c(void);
void sub_0c9b_083f(void);
void sub_0c9b_0861(int16_t x, int16_t y, int16_t id);
void sub_0c9b_08e8(void);
void sub_0c9b_0974(uint8_t *entry, uint8_t *pos, int16_t n);
void sub_0c9b_09ae(int16_t tile, int16_t side);
void sub_0c9b_0a15(int16_t horizon);
void sub_0c9b_0a66(int16_t horizon);
void sub_0c9b_0ae4(int16_t color, uint16_t src, int16_t x0, int16_t y0);
void sub_0c9b_0b20(void);
void sub_0c9b_0b85(int16_t y, int16_t nrows, int16_t color);
void sub_0c9b_0bba(int16_t y, int16_t nrows, int16_t color);
void sub_0c9b_0c0b(uint8_t *src, uint8_t *dst, int16_t y);
void sub_0c9b_0c40(uint8_t *src, uint8_t *dst, int16_t y);
void sub_0c9b_0c70(uint8_t *src, uint8_t *dst, int16_t y_unused);
void sub_0c9b_0ca6(uint8_t *src, uint8_t *dst, int16_t y_unused);
int16_t sub_0c9b_0e15(void);
void sub_0a86_0000(void);
void sub_0a86_01c6(void);
void sub_0a86_0298(void);
void sub_0a86_0325(void);
void sub_0a86_0370(int16_t sector);
void sub_0a86_0517(void);
void sub_0a86_06ee(void);
void sub_0a86_078e(void);
void sub_0a86_081f(int16_t spr, int16_t x, int16_t y, int16_t scale);
void sub_0a86_08d3(int16_t anim, int16_t x, int16_t y, int16_t scale);
void sub_0a86_09af(uint8_t *cell, int16_t side, int16_t layer);
void sub_0a86_0b29(uint8_t *cell, int16_t side);
void sub_0a86_0c88(uint8_t *cell, int16_t side);
void sub_0a86_0d96(int16_t y0);
void sub_0a86_0e25(void);
void sub_0a86_0e64(int16_t draw_actors);
int16_t sub_0a86_11ee(void);
void sub_0a86_12e5(void);
void sub_0a86_1341(void);
void sub_0a86_136f(void);
void sub_0a86_13a1(void);
void sub_0a86_13e2(void);
void sub_0a86_14ae(void);
void sub_0a86_1519(void);
void sub_0a86_1530(void);
void sub_0a86_154d(void);
void sub_0d84_0002(int16_t dx, int16_t dy, uint8_t *pts, uint16_t n, uint8_t color);  /* fills convex polygon of n int16 (x,y) pairs at pts, each offset by (dx,dy), solid color into drawbuf; Sutherland-Hodgman clip vs clip rect; nothing drawn if clipped to <=2 verts or ymin==ymax; uses DGROUP work area 0x2844..0x2d04 */
void sub_0d84_0235(int16_t xmin);  /* S-H clip current vertex list DS16(0x2844) (DS16(0x2cfe) edges) against x>=xmin into list DS16(0x2846); count->DS16(0x2d00), sets DS16(0x2d02)=1, closes output list and swaps 0x2844/0x2846 */
void sub_0d84_02b0(int16_t xmax);  /* same, keep x<=xmax */
void sub_0d84_032c(int16_t ymin);  /* same, keep y>=ymin (intersection x = x0+(ymin-y0)*dx/dy, endpoints not reordered) */
void sub_0d84_039e(int16_t ymax);  /* same, keep y<=ymax */
void sub_0dc5_0000(int16_t n);  /* scroll drawbuf rows [0x303c]..171 left by n px (row: memmove(row, row+n, ((320-n)>>1)*2)) */
void sub_0dc5_0040(int16_t n);  /* scroll drawbuf rows [0x303c]..171 right by n px (backward copy, starts at row 171) */
void sub_0dc5_007f(int16_t n, int16_t srcx);  /* after left scroll: per view row copy (n>>1)*2 bytes bgbuf[row+srcx] -> drawbuf[row+320-n] */
void sub_0dc5_00ca(int16_t n, int16_t srcx);  /* after right scroll: per view row copy (n>>1)*2 bytes bgbuf[row+320-srcx-n] -> drawbuf[row+0] */
void sub_0dc5_0117(void);  /* copy view rows [0x303c]..[0x3054) bgbuf -> drawbuf (restore background) */
void sub_0dc5_0148(void);  /* DS16(0x2d66)++ (frame counter); copy view rows [0x303c]..[0x3054) drawbuf -> screen; +plat_present() */
void sub_0dc5_017d(void);  /* DS16(0x17e2)=0; 7-pass interleaved dissolve drawbuf->screen, pass k copies bytes k+7i, i<7862 (rows 0..171), 2x sub_118f_00de (vsync) before each pass */
void sub_0dc5_01c5(void);  /* same dissolve over 9097*7 bytes (rows 0..198) */
void sub_0dc5_020d(uint8_t *src, uint8_t *dst);  /* copy 64000 bytes src->dst skipping color 0 (transparent overlay) */
void sub_0dc5_022e(void);  /* bgbuf sky gradient: scan 2-row bands bottom-up from row 171; from first band containing color 15, replace every 15 by 0xFF,0xFE.. (one value per 2-row band, stops decrementing at 0xE0) */
void sub_0dc5_026b(int16_t x, int16_t y);  /* magnify x4: 80x50 drawbuf window at (clamp(x-40,0,239),clamp(y-44,0,122)) -> full screen (offset 0) */
void sub_0dc5_02dd(int16_t x, int16_t y);  /* magnify x3: 106x66 window at (clamp(x-53,0,213),clamp(y-50,0,106)) -> screen, each row 318px+2 extra px of last color, last 2 screen rows cleared to 0 */
void sub_0dc5_0355(int16_t x, int16_t y);  /* magnify x2: 160x100 window at (clamp(x-80,0,159),clamp(y-80,0,72)) -> screen */
void sub_0dc5_03de(uint8_t *pal, int16_t r0, int16_t g0, int16_t b0, int16_t r1, int16_t g1, int16_t b1);  /* write 32-step gradient into palette entries 224..255 (pal+0x2a0): c[i] = (uint8)(((uint16)((c1-c0)*i) >> 5) + c0), i=0..31 */
void sub_0dc5_0448(uint8_t *src, uint8_t *dst, int16_t level);  /* 256-entry palette tint (level 0..16): R'=R+(((R+G+B+100)>>2)-R)*level>>4 (sar), G'=G*(16-level)>>4, B'=B*(16-level)>>4 */
void sub_0dc5_04b1(uint8_t *pts, uint8_t *out);  /* build byte lookup table by piecewise-linear interpolation: pts = u16 n, n x (int16 x, int16 v); writes one byte per x step (Bresenham, v low byte) plus a final byte */
void sub_0dc5_051b(uint8_t *src, uint8_t *dst);  /* half-size transparent blit: ((172-[0x303c])>>1) rows x 160 px, src pixel (2x,2y) -> dst (x,y) if !=0; both pitch 320 */
void sub_0dc5_0551(uint8_t *src, uint8_t *dst);  /* quarter-size transparent blit: ((172-[0x303c])>>2) rows x 80 px, src (4x,4y) -> dst (x,y) if !=0 */
void sub_0dc5_058d(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint8_t color);  /* Cohen-Sutherland clipped DASHED line into drawbuf (pattern 2 on/2 off, first pixel always on); zero-length line draws nothing; temps DS 0x2d06..0x2d0c */
void sub_0dc5_0780(void);  /* get time of day: DS8(0x3040)=hour, DS8(0x305e)=minute, DS8(0x3048)=second  -> plat_get_time() */
void sub_0e3f_00be(uint8_t *rgb, uint16_t first, uint16_t count);  /* set DAC entries first..first+count-1 from 6-bit RGB triplets -> plat_set_palette(first,count,rgb) */
void sub_0e3f_00de(uint8_t *pal);  /* in place: 768 bytes >>= 2 (8-bit -> 6-bit palette) */
void sub_0e3f_0104(void);  /* wait for start of vertical retrace -> plat_wait_vsync() */
int16_t sub_0e9b_000c(uint8_t *a, uint8_t *b);  /* rect overlap test, rects are int16 {x0,y0,x1,y1} inclusive: returns 1 if a.x0<=b.x1 && a.y0<=b.y1 && a.x1>=b.x0 && a.y1>=b.y0 (signed), else 0 */
uint16_t sub_0f21_0004(void);  /* game PRNG (not TC rand): 32-bit LFSR v=DS16(0x2d1c):DS16(0x2d1a), 16x { v=(v<<1)|(bit30^bit29) }, returns low word */
int32_t sub_0f23_000a(uint8_t *name);  /* size of file `name` (open/lseek end/close), -1 if it cannot be opened -> plat_file_size() */
uint8_t *sub_0f3a_0004(int16_t v);  /* signed int -> decimal string in static DSADDR(0x2d1e) (no leading zeros, '-' if negative), returns that pointer (custom itoa, not TC's) */
uint16_t sub_0f3a_00d3(uint16_t v, uint16_t div, int16_t *started, uint8_t **out);  /* near digit emitter: q=v/div; emits '0'+q if q!=0 or *started (then *started=1); returns v%div */
void sub_0fe6_01ac(int16_t xmin, int16_t xmax);  /* SS16(0x196)=xmin, SS16(0x198)=xmax */
void sub_0fe6_01bf(int16_t ymin, int16_t ymax);  /* SS16(0x192)=ymin, SS16(0x194)=ymax */
void sub_0fe6_01d2(uint16_t id, int16_t x, int16_t y, uint8_t *dst, uint8_t *bank);  /* draw RLE sprite (id&0xfff) of bank into dst (pitch 320) with left x and BOTTOM row y, clipped to clip rect; id&0x8000 = mirrored (re-mirrors sprite data IN PLACE if its flag word differs), id&0x4000 = opaque (transparent runs written as 0) */
void sub_1036_000a(uint8_t *src, uint8_t *dst);  /* copy 64000 bytes src -> dst (full screen buffer copy) */
void sub_103b_0004(uint8_t *src, int16_t sx, int16_t sy, uint8_t *dst, int16_t dx, int16_t dy, uint16_t w, uint16_t h);  /* copy w x h rectangle, both pitch 320, src(sx,sy) -> dst(dx,dy); per row (uint8)(w>>1) words + (w&1) bytes */
void sub_1040_0006(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint8_t color);  /* solid line into drawbuf: y0==y1 -> clipped hline fast path; else Cohen-Sutherland clip + Bresenham; clipped zero-length line draws nothing; temps DS 0x2d84..0x2d8a */
void sub_1040_023a(int16_t x0, int16_t y, int16_t x1, uint8_t color);  /* horizontal line x0..x1 (x0<=x1) at y in drawbuf, clipped to clip rect */
void sub_106a_0407(uint8_t flags);  /* set coord-decode state of sub_106a_0477 (was code patching): cs:0xc = flags (0x10 int8 coords, 0x80 negate x, 0x20 negate y) */
void sub_106a_043f(uint8_t flags);  /* same for sub_106a_04ff: cs:0xd = flags */
void sub_106a_0477(uint16_t id, int16_t x, int16_t y, uint8_t *shp);  /* draw vector shape (id&0xfff) of shape file shp at (x,y); id high byte 0x80 = mirror x, 0x20 = mirror y; vertices decoded per flags, + (x,y), then primitive handler */
void sub_106a_04ff(uint16_t id, int16_t x, int16_t y, uint8_t *shp, int16_t scale);  /* same, vertices scaled: (int16)((int32)v*scale >> 8) + x/y  (scale 8.8, 256 = 1:1) */
void sub_106a_0593(uint16_t id, int16_t x, int16_t y, uint8_t *shp, uint16_t angle);  /* same, vertices rotated by angle&0xff (256 = full turn, sine table DS16(0x2d8c), 16383 = 1.0): x'=((vx*cos - vy*sin)>>14)+x, y'=((vy*cos + vx*sin)>>14)+y; always int16 coords, NO mirroring (original patches 04ff's code by mistake) */
void sub_106a_06a1(uint16_t unused, int16_t x, int16_t y, uint8_t *shp, uint16_t t);  /* draw morph shape (always shape #0 of shp): each vertex a+(b-a)*t>>8 (t 0..256); color pair per primitive chosen by prim index vs (t*nprims)>>8 */
void sub_10f5_0028(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint8_t color);  /* filled rectangle (inclusive) into drawbuf, clamped to clip rect; nothing drawn if (clamped) x1<=x0 or y1<=y0 */
void sub_1100_000b(int16_t x, int16_t y);  /* plot pixel in current point color (static, set by sub_1100_00c0) into drawbuf if inside clip rect */
void sub_1100_0096(int16_t x, int16_t y);  /* plot pixel in current point color, no clipping */
void sub_1100_00c0(uint8_t color);  /* set current point color */
uint8_t sub_110c_000c(int16_t x, int16_t y);  /* read pixel of drawbuf at (x,y), no clipping */
uint8_t *sub_1110_01bc(uint16_t idx, uint16_t level, uint8_t *bank, uint8_t *dst);  /* build a shrunk copy of sprite idx (no mask) as a 1-sprite bank at dst: level 0..14 keeps level+1 of every 16 columns (fixed pattern) and rows whose (1<<(rowsleft&15)) is in a mask; re-RLE-encodes; returns pointer to end of written data */
uint16_t sub_115f_000c(uint16_t id, uint8_t *bank);  /* width in pixels (byte0*16) of sprite id&0xfff in bank */
uint16_t sub_115f_0054(uint16_t id, uint8_t *bank);  /* height (byte1) of sprite id&0xfff in bank */
void sub_116d_000c(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint8_t color);  /* rectangle outline: hline y0, hline y1 (sub_1040_023a), vlines x0 and x1 (sub_1040_0006) */
void sub_1172_0012(int16_t x, int16_t y, uint8_t *dst, uint8_t *str);  /* draw NUL-terminated string with current font/color at (x,y) (top-left) into dst (320 pitch; ORIGINAL USES ONLY THE SEGMENT of dst, i.e. offset treated as 0); 1bpp glyphs, set bits drawn, no clipping; pen x left in static cs:0x10 */
void sub_1172_011d(uint8_t *font, uint8_t color);  /* select font (parse header into statics) and text color */
int16_t sub_1172_018c(uint8_t *str);  /* pixel width of string in current font: sum(glyphw ? glyphw : 2) + 1 per char */
void sub_0000_0000(void);  /* C0 startup (replaced by src/main.c) */
_Noreturn void sub_0000_010d(int16_t status);  /* _exit */
void sub_0000_012f(void);  /* save/hook CPU exception vectors (no-op) */
void sub_0000_0172(void);  /* restore CPU exception vectors (no-op) */
void sub_0000_01a7(void);  /* write to stderr (startup internal) */
_Noreturn void sub_0000_01af(void);  /* abort */
void sub_0000_01d0(void);  /* _setargv (no-op) */
void sub_0000_025e(void);  /* _setargv helper (no-op) */
void sub_0000_02ce(void);  /* _setenvp (no-op) */
void sub_0d7d_000a(void);  /* install fps-meter timer hook */
void sub_0d7d_002e(void);  /* remove fps-meter timer hook */
void sub_0d7d_0046(void);  /* fps-meter timer ISR */
int32_t sub_0e66_0006(int32_t h, int32_t off, int32_t whence);  /* lseek (whence -1 SET, 0 CUR, 1 END); 0 ok, -1 error */
int32_t sub_0e66_0031(uint8_t *name, int16_t mode);  /* open (0x3ed read, 0x4d2 r/w, 0x3ee create); handle or 0 */
int32_t sub_0e66_0114(int32_t h, uint8_t *buf, int32_t n);  /* write, returns bytes written */
int32_t sub_0e66_0191(int32_t h, uint8_t *buf, int32_t n);  /* read, returns bytes read */
int32_t sub_0e66_022b(int32_t h);  /* close */
int32_t sub_0e9f_0013(int16_t param, uint16_t mask, uint16_t cmd);  /* sound driver fn 0x0a: music control */
void sub_0e9f_006f(int16_t effect, int16_t unused, uint16_t cmd);  /* play/stop sound effect n */
void sub_0e9f_00c1(void);  /* sound driver init */
void sub_0e9f_0116(void);  /* sound driver timer tick callback */
void sub_0e9f_011f(void);  /* sound driver shutdown */
void sub_0e9f_017e(int16_t unused, uint8_t *bank);  /* set SFX bank */
void sub_0e9f_01a8(int16_t unused, uint8_t *song);  /* load + start song */
void sub_0ebb_01d2(uint8_t scancode);  /* keyboard ISR (one raw scancode) */
void sub_0ebb_0301(void);  /* install keyboard handler */
void sub_0ebb_0363(void);  /* remove keyboard handler */
void sub_0ebb_0372(void);  /* timer callback: virtual cursor */
void sub_0ebb_037f(uint8_t dir);  /* virtual cursor move */
void sub_0ebb_03aa(void);  /* virtual cursor clamp */
void sub_0efe_0030(void);  /* empty timer hook */
void sub_0efe_0031(void);  /* program PIT from DS16(0x2d14) */
void sub_0efe_004b(void);  /* install timer */
void sub_0efe_0158(void (*fn)(void));  /* register timer callback */
void sub_0efe_016f(void (*fn)(void));  /* register timer callback (duplicate) */
void sub_0efe_0186(void (*fn)(void));  /* register helper */
void sub_0efe_01c0(void (*fn)(void));  /* unregister timer callback */
void sub_0efe_01d5(void (*fn)(void));  /* unregister helper */
void sub_0efe_0202(void);  /* uninstall timer */
uint8_t *sub_0f27_0004(int32_t size);  /* farmalloc; farmalloc(-1) returns farcoreleft() cast to a pointer-sized number: use sys_farcoreleft() instead */
int16_t sub_0f27_0061(uint8_t *p);  /* farfree, returns -1 */
int32_t sub_0f27_0079(uint8_t *p, int32_t size);  /* resize block in place, -1 ok */
void sub_0f32_000d(uint8_t *dst, uint8_t *name, uint8_t *ext);  /* strcpy + add extension if none */
void sub_0f48_0029(void);  /* explode helper (internal) */
void sub_0f48_02ab(void);  /* explode helper (internal) */
void sub_0f48_0314(uint16_t flags, uint8_t *src, uint8_t *dst, int32_t outlen, uint8_t *work);  /* PKWARE explode */
uint8_t sub_0fa2_0008(uint8_t *name, int16_t index, uint8_t *dst);  /* load PAK entry into dst; 1 ok */
void sub_118f_0004(void);  /* video init */
void sub_118f_00cd(void);  /* restore video mode */
void sub_118f_00de(void);  /* wait vertical retrace */
void sub_118f_00f7(void);  /* clear back buffer */
void sub_118f_0107(void);  /* present back buffer to screen */
void sub_118f_01ab(uint8_t *rgb, int16_t first, int16_t count);  /* set DAC from 8-bit RGB */
void sub_11b2_0001(void);  /* system init: back buffer, video, timer */
void sub_11b2_0043(void);  /* system shutdown */
int16_t sub_11b7_000d(int16_t doserr);  /* __IOerror */
void sub_11bb_0008(void);  /* empty exit hook */
_Noreturn void sub_11bb_0009(int16_t status);  /* exit */
uint8_t *sub_11c1_000b(uint16_t n);  /* malloc */
void sub_11c1_0020(void);  /* RTL heap internal */
void sub_11c1_0088(void);  /* RTL heap internal */
void sub_11c1_0138(void);  /* RTL heap internal */
void sub_11c1_01a6(void);  /* RTL heap internal */
uint8_t *sub_11c1_020c(uint32_t n);  /* RTL farmalloc */
void sub_11f2_000b(void);  /* __brk */
void sub_11f2_00e2(void);  /* __sbrk */
int16_t sub_1207_000d(uint16_t seg, uint16_t paras);  /* setblock */
void sub_1209_000d(uint8_t *dst, uint16_t len, uint8_t val);  /* setmem (TC order) */
void sub_120e_0002(uint8_t *src, uint8_t *dst, uint16_t len);  /* movmem: SOURCE FIRST */
int16_t sub_1215_0017(void);  /* rand() */
int32_t sys_farcoreleft(void);  /* = farmalloc(-1L) in the original */
uint8_t *sys_launcher_config(void);  /* launcher parameter block (CONFIG.TAT), = far ptr at 0000:025c */

#endif
