"""Generate src/game/codeptrs.c: C functions for far code pointers stored in DGROUP."""
import sys; sys.path.insert(0, 'tools')
from mz import MZ
m = MZ('re/unpacked/AVE.CC1.3.bin'); DG = 0x1219
refs = set()
for seg, off in m.relocs:
    l = seg*16 + off
    if l >= DG*16 + 2:
        sv = m.w(l); ov = m.w(l-2)
        if sv < DG: refs.add((sv, ov))
out = ['/* Generated by tools/gen_codeptrs.py: far code pointers found in DGROUP */',
       '#include "../core/loader.h"', '#include "protos.h"', '',
       'static const struct { uint16_t seg, off; void *fn; } tab[] = {']
for s, o in sorted(refs):
    out.append('    { 0x%04x, 0x%04x, (void *)sub_%04x_%04x },' % (s, o, s, o))
out += ['};', '', 'void *code_ptr_lookup(uint16_t seg, uint16_t off) {',
        '    for (unsigned i = 0; i < sizeof tab / sizeof tab[0]; i++)',
        '        if (tab[i].seg == seg && tab[i].off == off) return tab[i].fn;',
        '    return NULL;', '}', '']
open('src/game/codeptrs.c', 'w').write('\n'.join(out))
print(len(refs), sorted('%04x:%04x' % r for r in refs))
