"""Merge re/protos/G*.h into src/game/protos.h; report duplicates/missing functions."""
import re, glob, collections, subprocess
allf = [l.split()[1] for l in open('re/ave3.asm') if l.startswith('; sub_')]
decl = collections.OrderedDict(); dup = []
for fn in sorted(glob.glob('re/protos/G*.h'), key=lambda s: int(re.search(r'G(\d+)', s).group(1))):
    for line in open(fn):
        m = re.search(r'\b((?:sub_[0-9a-f]{4}_[0-9a-f]{4})|sys_\w+)\s*\(', line)
        if not m or line.strip().startswith(('//', '*', '/*')) and '(' not in line.split('/*')[0]: continue
        name = m.group(1)
        if name not in allf and not fn.endswith('G10.h'): continue   # hidden/local helpers stay static in their .c file
        code = line.split('/*')[0].split('//')[0].strip()
        if not code.endswith(';'): continue
        code = re.sub(r'^\s*static\s+', '', code)
        cmt = line[len(line.split('/*')[0]):].strip() if '/*' in line else ''
        if name in decl: dup.append((name, decl[name][0], code))
        else: decl[name] = (code, cmt, fn)
missing = [f for f in allf if f not in decl]
out = ['/* Prototypes of all decompiled functions (merged from re/protos). Generated by tools/merge_protos.py */',
       '#ifndef ETERNAM_PROTOS_H', '#define ETERNAM_PROTOS_H', '#include <stdint.h>', '']
for name, (code, cmt, fn) in decl.items():
    out.append(code + ('  ' + cmt if cmt else ''))
out += ['', '#endif', '']
open('src/game/protos.h', 'w').write('\n'.join(out))
print('declared', len(decl), 'dups', len(dup), 'missing', len(missing))
for d in dup: print('DUP', d)
print('MISSING', ' '.join(missing[:200]))
r = subprocess.run(['clang', '-fsyntax-only', '-x', 'c', 'src/game/protos.h'], capture_output=True, text=True)
print(r.stderr[:3000] or 'syntax OK')
